tap "homebrew/bundle"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "mas"
brew "nvm"
brew "pinentry-mac"
cask "alacritty"
cask "brave-browser"
cask "discord"
cask "font-hack-nerd-font"
cask "openvpn-connect"
mas "LINE", id: 539883307
