[[plugins]]
repo = "Shatur/neovim-ayu"
hook_add = """
colorscheme ayu-light
"""

[[plugins]]
repo = "windwp/nvim-autopairs"
lua_add = """
require("nvim-autopairs").setup()
"""

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
lua_add = """
require("nvim-treesitter.configs").setup({
	highlight = {
		enable = true,
	},
})
"""

[[plugins]]
repo = "Shougo/ddu.vim"
lua_add = """
vim.fn["ddu#custom#patch_global"]({
	ui = "filer",
	sources = {
	    	{
	      		name = "file",
	      		params = {},
	    	},
	},
	sourceOptions = {
	    	_ = {
	      		columns  = { "filename" },
	    	},
	},
	kindOptions = {
		file = {
	      		defaultAction = "open",
	    	},
	},
})

vim.api.nvim_create_autocmd("FileType", {
	pattern = "ddu-filer",
  	callback = function()
    		local opts = { noremap = true, silent = true, buffer = true }

    		vim.keymap.set("n", "<CR>",    "<Cmd>call ddu#ui#do_action('itemAction')<CR>", opts)
    		vim.keymap.set("n", "<Space>", "<Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>", opts)
    		vim.keymap.set("n", "o",       "<Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>", opts)
    		vim.keymap.set("n", "q",       "<Cmd>call ddu#ui#do_action('quit')<CR>", opts)
  	end,
})
"""

[[plugins]]
repo = "Shougo/ddu-source-file"

[[plugins]]
repo = "Shougo/ddu-kind-file"

[[plugins]]
repo = "Shougo/ddu-column-filename"

[[plugins]]
repo = "Shougo/ddu-ui-filer"
